version: '3.8'

networks:
  larvarel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - larvarel
  
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - larvarel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php 
    volumes:
      - ./src:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "9000:9000"
    networks:
      - larvarel

  